[ids]
*

[main]
# Left Alt acts as Left Control
leftalt = leftcontrol

# Right Control as Mode Switch
rightalt = layer(myswitch)

# Backslash key as Backspace
backslash = backspace

leftcontrol = esc

rightsuper = rightalt

# Define the 'myswitch' layer for mode switching
[myswitch]
tab = ~
q = !
z = @
b = #
g = $
t = %
y = &
u = *
i = (
o = )
p = +
n = _
m = -
apostrophe = `
semicolon = ^
[ = backslash
] = |
comma = =

a = 0
w = 1
e = 2
r = 3
s = 4
d = 5
f = 6
x = 7
c = 8
v = 9

h = left
j = down
k = up
l = right
