#!/bin/bash

main() {
    source ~/.config/Scripts/color.sh
    [[ $BUTTON = 2 ]] && setsid st -e e ~/.config/Scripts/battery

    local full_charged="fully-charged"
    local charging="charging"
    local discharge="discharging"

    local full_power_status=$(upower -i $(upower -e | grep BAT) | grep --color=never state)
    local power_status=${full_power_status/state: /}

    [ -f "/sys/class/power_supply/BAT0/capacity" ] && percentage=$(cat /sys/class/power_supply/BAT0/capacity) || exit

    # typicons (~/.local/share/fonts/typicons): plug, battery-charge, battery-{full,high,mid,low}
    [ $power_status = $full_charged ] && printf "%s ${percentage}%%\n" $'\ue0cd'
    [ $power_status = $charging ] && echo $'\ue02a'" $percentage%"

    if [ $power_status = $discharge ]; then
        local icon=$'\ue02d'
        [ $percentage -ge 20 ] && icon=$'\ue02e'
        [ $percentage -ge 50 ] && icon=$'\ue02c'
        [ $percentage -ge 80 ] && icon=$'\ue02b'
        echo "$icon $percentage%"
    fi
}

#main
