#!/usr/bin/env bash
#this script helps to select monitor, change monitor mode (mirror or independent)

get_aval_monitor_num() {
    local mon_num=$(xrandr --listactivemonitors | grep "Monitors: ")
    mon_num=${mon_num/Monitors: /}
    echo $mon_num
}


mon_list=()
get_monitors() {
    echo "Get active monitors"
   local all_mons=$(xrandr -q)
   mon=$(xrandr | egrep -o "^[A-Za-z0-9\-]* connected")
   for i in ${mon[@]}; do
       [ $i = "connected" ] || mon_list=(${mon_list[@]} $i)
   done
   echo "find ${#mon_list[@]} monitors"
}

set_mirror() {
    local left=""
    for i in ${mon_list[@]}; do
        if [ -z $left ]; then
            # the first mon
            xrandr --output $i --auto
        else
            xrandr --output $i --same-as $left --auto
        fi
        left=$i
    done
}

set_indep_left_to_right_by_index() {
    # set other mon to the right-of the previous one
    local left=""
    for i in ${mon_list[@]}; do
        echo "set monitor ${i}"
        if [ -z $left ]; then
            # the first mon
            xrandr --output $i --auto
        else
            xrandr --output $i --right-of $left --auto
        fi
        left=$i
    done
    local bgloc="$HOME/.local/share/bg"
    xwallpaper --zoom "$bgloc"
}

get_current_monitor() {
    # monitor under the mouse cursor
    eval "$(xdotool getmouselocation --shell)"
    while read -r line; do
        if [[ "$line" =~ ^([A-Za-z0-9-]+)[[:space:]]+connected.*[[:space:]]([0-9]+)x([0-9]+)\+([0-9]+)\+([0-9]+) ]]; then
            local name="${BASH_REMATCH[1]}"
            local w="${BASH_REMATCH[2]}"
            local h="${BASH_REMATCH[3]}"
            local mx="${BASH_REMATCH[4]}"
            local my="${BASH_REMATCH[5]}"
            if (( X >= mx && X < mx + w && Y >= my && Y < my + h )); then
                echo "$name"
                return
            fi
        fi
    done < <(xrandr -q)
}

set_current_as_main_left() {
    # set the monitor under the cursor as primary at 0,0; place the rest to its right
    local current=$(get_current_monitor)
    if [ -z "$current" ]; then
        notify-send "Monitor" "Cannot detect current monitor" -t 3000
        return 1
    fi
    echo "current monitor: $current"
    xrandr --output "$current" --primary --pos 0x0 --auto
    local prev="$current"
    for i in ${mon_list[@]}; do
        if [ "$i" != "$current" ]; then
            echo "set monitor $i right-of $prev"
            xrandr --output "$i" --right-of "$prev" --auto
            prev="$i"
        fi
    done
    local bgloc="$HOME/.local/share/bg"
    [ -f "$bgloc" ] && xwallpaper --zoom "$bgloc"
}

sel_from_dmenu() {
    if [ $1 > 1 ]; then
        mode=$(echo -e "mirror\nindependent\ncurrent-as-main" | dmenu)
        case $mode in
            "mirror")
                set_mirror
                ;;
            "independent")
                set_indep_left_to_right_by_index
                ;;
            "current-as-main")
                set_current_as_main_left
                ;;
        esac

    else
        notify-send "Monitor" "Single monitor does not need setting" -t 3000
    fi
}

main() {
    local monitor_num=$(get_aval_monitor_num)
    get_monitors
    if [ ${#@} = 0 ]; then
        sel_from_dmenu $monitor_num
    else
        if [ ${#@} = 1 ]; then
            case $1 in
                init)
                    set_indep_left_to_right_by_index && notify-send "Monitor" "Set monitor to independent mode" -t 3000
                    ;;
                current)
                    set_current_as_main_left && notify-send "Monitor" "Set current monitor as main (left)" -t 3000
                    ;;
                *)
                    echo "wrong param"
                    ;;
            esac
        else
            echo "wrong param"
        fi
    fi
}

main $@
