#!/usr/bin/env bash

case $BUTTON in
    1) setsid st -e htop;;
    2) setsid st -e emacsclient -nc "~/.config/Scripts/show_resource" ;;
esac

# typicons chart-bar + used/total memory
echo $'\ue041' $(free -h | awk '/^Mem/ { print $3"/"$2 }' | sed s/i//g)
